# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wasp_custom_msgs/object_loc.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class object_loc(genpy.Message):
  _md5sum = "7a1c2314593d80d85bf881c56f7c895d"
  _type = "wasp_custom_msgs/object_loc"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Custom message for publishing the detected object position
#object_loc.msg
int16 ID
geometry_msgs/Point point
geometry_msgs/Point angles

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['ID','point','angles']
  _slot_types = ['int16','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,point,angles

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(object_loc, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      if self.angles is None:
        self.angles = geometry_msgs.msg.Point()
    else:
      self.ID = 0
      self.point = geometry_msgs.msg.Point()
      self.angles = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_h6d.pack(_x.ID, _x.point.x, _x.point.y, _x.point.z, _x.angles.x, _x.angles.y, _x.angles.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      if self.angles is None:
        self.angles = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 50
      (_x.ID, _x.point.x, _x.point.y, _x.point.z, _x.angles.x, _x.angles.y, _x.angles.z,) = _struct_h6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_h6d.pack(_x.ID, _x.point.x, _x.point.y, _x.point.z, _x.angles.x, _x.angles.y, _x.angles.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      if self.angles is None:
        self.angles = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 50
      (_x.ID, _x.point.x, _x.point.y, _x.point.z, _x.angles.x, _x.angles.y, _x.angles.z,) = _struct_h6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_h6d = struct.Struct("<h6d")
